using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models.Common.Policy.Enum;
public enum MarineClauses
{
    [Description("INLAND TRANSIT (RAIL OR ROAD) CLAUSE (B)")]
    INLANDTRANSIT = 1,
    [Description("STRIKE RIOTS AND CIVIL COMMOTION CLAUSE")]
    STRIKERIOTS = 2,
    [Description("NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE")]
    CANCELLATION = 3,
    [Description("TERMINATION OF TRANSIT CLAUSE (TERRORISM)")]
    TRANSITCLAUSE = 4,
    [Description("INSTITUTE CARGO CLAUSES 'AIR' (INCLUDING TPND)")]
    CARGOCLAUSES = 5,
    [Description("INSTITUTE STRIKE CLAUSES 'AIR CARGO' INCLUDING TERRORISM")]
    STRIKECLAUSES = 6,
    [Description("INSTITUTE WAR CLAUSE 'AIR CARGO'")]
    WARCLAUSE = 7,
    [Description("NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE")]
    AUTOMATICTERMINATIONCLAUSE = 8,
    [Description("TERMINATION OF TRANSIT CLAUSE (TERRORISM)")]
    TERMINATIONOFTRANSITCLAUSE = 9,
    [Description("INSTITUE WAR CANCELLATION CLAUSE (CARGO)")]
    WARCANCELLATIONCLAUSE = 10,
    [Description("INSTITUTE CARGO CLAUSE 'A' INCLUDING TPND")]
    INSTITUTECARGOCLAUSE = 11,
    [Description("INLAND TRANSIT (RAIL AND ROAD) CLAUSE (A) INCLUDING (TPND)")]
    INLANDTRANSITCLAUSE = 12,
    [Description("INSTITUTE STRIKE CLAUSES 'CARGO' INCLUDING TERRORISM")]
    INSTITUTESTRIKECLAUSE = 13,
    [Description("INSTITUTE WAR CLAUSE 'CARGO'")]
    INSTITUTEWARCLAUSE = 14,
    [Description("NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE")]
    NOTICEOFAUTOMATICTERMINATIONCLAUSE = 15,
    [Description("TERMINATION OF TRANSIT CLAUSE (TERRORISM)")]
    TERMINATIONTRANSITCLAUSE = 16,
    [Description("INSTITUE WAR CANCELLATION CLAUSE (CARGO)")]
    INSTITUEWARCANCELLATIONCLAUSE = 17,
    [Description("INSTITUTE CLASSIFICATION CLAUSE")]
    CLASSIFICATIONCLAUSE = 18,
    [Description("INLAND TRANSIT (RAIL OR ROAD) CLAUSE (A) INCLUDING (TPND)")]
    INLANDTRANSITRAILORROAD = 19,
    [Description("STRIKE RIOTS AND CIVIL COMMOTION CLAUSE (INLAND TRANSIT NOT IN CONJUCTION WITH OCEAN GOING VOYAGE)")]
    CIVILCOMMOTIONCLAUSE = 20,
    [Description(" TERMINATION OF TRANSIT CLAUSE (TERRORISM)")]
    TERMINATIONTRANSIT = 21,
    [Description("NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE")]
    NOTICEOFCANCELLATIONCLAUSE = 22,
    [Description("ELECTRICAL AND MECHANICAL DERRAGEMENT")]
    MECHANICALDERRAGEMENT = 23,
    [Description("DUTY INSURANCE CLAUSE")]
    DUTYINSURANCECLAUSE = 24,
    [Description("PRE-DESPATCH SURVEY CLAUSE")]
    PREDESPATCHCLAUSE = 25,
    [Description("THEFT, PILFERAGE AND NON DELIVERY CLAUSE")]
    THEFTPILFERAGEANDNONDELIVERYCLAUSE = 26,
    [Description("REPLACEMENT CLAUSE (SECOND HAND MACHINERY)")]
    REPLACEMENTCLAUSE = 27,
    [Description("DURATION OF COVER EXTENSION CLAUSE")]
    EXTENSIONCLAUSE = 28,
}

public class ClausesDictionary
{
    public static Dictionary<int, string> marineClauses()
    {
        Dictionary<int, string> Clauses = new Dictionary<int, string>()
                {
                {1 ,"INLAND TRANSIT (RAIL OR ROAD) CLAUSE (B)"},
               {2,"STRIKE RIOTS AND CIVIL COMMOTION CLAUSE (including SRCC and Terrorism)"},
               {3,"NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE"},
              {4,"TERMINATION OF TRANSIT CLAUSE (TERRORISM)"},
              {5,"INSTITUTE CARGO CLAUSES 'AIR' (INCLUDING TPND)"},
              {6,"INSTITUTE STRIKE CLAUSES 'AIR CARGO' INCLUDING SRCC AND TERRORISM"},
              {7,"INSTITUTE WAR CLAUSE 'AIR CARGO'"},
              {8,"NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE"},
              {9,"TERMINATION OF TRANSIT CLAUSE (TERRORISM)"},
              {10,"INSTITUE WAR CANCELLATION CLAUSE (CARGO)"},
              {11,"INSTITUTE CARGO CLAUSE 'A' INCLUDING TPND"},
              {12,"INLAND TRANSIT (RAIL OR ROAD) CLAUSE (A) INCLUDING (TPND)"},
              {13,"INSTITUTE STRIKE CLAUSES 'CARGO' INCLUDING SRCC AND TERRORISM"},
              {14,"INSTITUTE WAR CLAUSE 'CARGO'"},
              {15,"NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE"},
              {16,"TERMINATION OF TRANSIT CLAUSE (TERRORISM)"},
              {17,"INSTITUE WAR CANCELLATION CLAUSE (CARGO)"},
              {18,"INSTITUTE CLASSIFICATION CLAUSE"},
              {19,"INLAND TRANSIT (RAIL OR ROAD) CLAUSE (A) INCLUDING (TPND)"},
              {20,"STRIKE RIOTS AND CIVIL COMMOTION CLAUSE (INLAND TRANSIT NOT IN CONJUCTION WITH OCEAN GOING VOYAGE)"},
              {21,"TERMINATION OF TRANSIT CLAUSE (TERRORISM)"},
              {22,"NOTICE OF CANCELLATION AND AUTOMATIC TERMINATION CLAUSE"},
              {23,"ELECTRICAL AND MECHANICAL DERRAGEMENT"},
              {24,"DUTY INSURANCE CLAUSE"},
              {25,"PRE-DESPATCH SURVEY CLAUSE"},
              {26,"THEFT, PILFERAGE AND NON DELIVERY CLAUSE"},
              {27,"REPLACEMENT CLAUSE (SECOND HAND MACHINERY)"},
              {28,"DURATION OF COVER EXTENSION CLAUSE"},
              {29,"INLAND TRANSIT (RAIL OR ROAD) CLAUSE (C)"},
              {30,"INSTITUTE CARGO CLAUSE (C)"},
              {31,"INSTITUTE CARGO CLAUSE (C) INCLUDING TPND"},
              {32,"INLAND TRANSIT (RAIL OR ROAD) CLAUSE(C)"},
              {33,"INSTITUTE TRANSIT (RAIL OR ROAD) Clause (C) INCLUDING TPND"},
                };
        return Clauses;
    }

}
