services:


  # ----------------- Beema Edge API -----------------
  bmseapi:
    container_name: bmsapi
    restart: always
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Dev"
      Seq__ServerUrl: "http://seq:80"
      Serilog__WriteTo__0__Name: "Seq"
      Serilog__WriteTo__0__Args__serverUrl: "http://seq:80"

      # Required for nginx-proxy + SSL
      VIRTUAL_HOST: api-bms.beemaedge.com
      LETSENCRYPT_HOST: api-bms.beemaedge.com
      LETSENCRYPT_EMAIL: sthaejan00@gmail.com
      VIRTUAL_PORT: 8081

      # PostgreSQL connection string
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=bms;Username=beemauser;Password=beemapass;Pooling=true;"
    expose:
      - "8081"
    volumes:
      - /root/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - proxy

    # ----------------- Beema Edge CMS (Next.js) -----------------
    bmscms:
      container_name: bmscms
      restart: always
      build:
        context: /home/ubuntu/app/bms/budget360frontend
        dockerfile: Dockerfile            # Use your CMS Dockerfile
      env_file:
        - /home/ubuntu/app/.secrets/.env.frontend.dev 
      environment:
        # For nginx-proxy SSL routing
        VIRTUAL_HOST: "bms.beemaedge.com,hei-bms.beemaedge.com,uail-bms.beemaedge.com"
        LETSENCRYPT_HOST: "bms.beemaedge.com,hei-bms.beemaedge.com,uail-bms.beemaedge.com"
        LETSENCRYPT_EMAIL: sthaejan00@gmail.com
        VIRTUAL_PORT: 3000             # Next.js runs on 3000 by default

      expose:
        - "3000"
      networks:
        - proxy


# ----------------- NETWORKS -----------------
networks:
  proxy:
    external: true
    name: beemaedge_proxy
