// <auto-generated />
using System;
using System.Collections.Generic;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations.Core
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20250711122722_ITIFamilyMembers_Table_added")]
    partial class ITIFamilyMembers_Table_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.AdminEntity.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Data.Entities.AgentEntity.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("UserId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Data.Entities.Common.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryDialingCode")
                        .HasColumnType("text");

                    b.Property<string>("CountryFlagIcon")
                        .HasColumnType("text");

                    b.Property<string>("CountryISO2")
                        .HasColumnType("text");

                    b.Property<string>("CountryISO3")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CountryISO2")
                        .IsUnique();

                    b.HasIndex("CountryName")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Data.Entities.CorporateEntity.Corporate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CorporateName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Corporates");
                });

            modelBuilder.Entity("Data.Entities.CustomerEntity.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CitizenshipIssueDate")
                        .HasColumnType("text");

                    b.Property<string>("CitizenshipIssueDistrict")
                        .HasColumnType("text");

                    b.Property<string>("CitizenshipNo")
                        .HasColumnType("text");

                    b.Property<string>("CoreSyncStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourtesyTitle")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DIANumber")
                        .HasColumnType("text");

                    b.Property<string>("DigitalSignature")
                        .HasColumnType("text");

                    b.Property<string>("DobAD")
                        .HasColumnType("text");

                    b.Property<string>("DobBS")
                        .HasColumnType("text");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("FullNameNepali")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("GrandFatherName")
                        .HasColumnType("text");

                    b.Property<string>("IdBackPhoto")
                        .HasColumnType("text");

                    b.Property<string>("IdFrontPhoto")
                        .HasColumnType("text");

                    b.Property<string>("IndividualType")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KycRejectedReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("KycReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KycReviewedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("LicenseExpiryDate")
                        .HasColumnType("text");

                    b.Property<string>("LicenseIssueDate")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("NIDNumber")
                        .HasColumnType("text");

                    b.Property<List<string>>("OccupationJson")
                        .HasColumnType("text[]");

                    b.Property<string>("PanNo")
                        .HasColumnType("text");

                    b.Property<string>("PartyCode")
                        .HasColumnType("text");

                    b.Property<string>("PartyID")
                        .HasColumnType("text");

                    b.Property<string>("PassportExpiryDate")
                        .HasColumnType("text");

                    b.Property<string>("PassportIssueDate")
                        .HasColumnType("text");

                    b.Property<string>("PassportIssuePlace")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("text");

                    b.Property<string>("VoterIdNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KycReviewedByUserId");

                    b.HasIndex("PanNo")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Data.Entities.CustomerEntity.CustomerAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<int?>("Ward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Data.Entities.Draft.PolicyDraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BancassuanceBankBranch")
                        .HasColumnType("text");

                    b.Property<string>("BancassuanceBankName")
                        .HasColumnType("text");

                    b.Property<decimal>("BasicPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("DraftNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GovernmentSubsidyAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("ITIId")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotorId")
                        .HasColumnType("text");

                    b.Property<decimal>("NetPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PayableAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentGateway")
                        .HasColumnType("text");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("text");

                    b.Property<decimal>("PersonalAccidentPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text");

                    b.Property<string>("PortfolioAlias")
                        .HasColumnType("text");

                    b.Property<string>("PortfolioId")
                        .HasColumnType("text");

                    b.Property<string>("PortfolioParent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProposedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RSMDTPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<List<string>>("ShareCompanyLists")
                        .HasColumnType("text[]");

                    b.Property<decimal>("StampDuty")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThirdPartyPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfParty")
                        .HasColumnType("text");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("privateVehicleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ITIId");

                    b.HasIndex("MotorId");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique();

                    b.HasIndex("privateVehicleId");

                    b.ToTable("PolicyDrafts");
                });

            modelBuilder.Entity("Data.Entities.EmailLogEntity.EmailLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bcc")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("Cc")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EmailType")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("Data.Entities.ITIEntity.ITIFamilyMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<int>("InternationalTravelInsuranceId")
                        .HasColumnType("integer");

                    b.Property<string>("InternationalTravelInsuranceId1")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("Relation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InternationalTravelInsuranceId1");

                    b.ToTable("ITIFamilyMembers");
                });

            modelBuilder.Entity("Data.Entities.ITIEntity.InternationalTravelInsurance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDateBeforeEndorsement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ExpiryDateBeforeEndorsement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherHusbandName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("PolicyPeriodInDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("TravellingCountry")
                        .HasColumnType("text");

                    b.Property<string>("TripType")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfInsured")
                        .HasColumnType("text");

                    b.Property<string>("VisitingCountry")
                        .HasColumnType("text");

                    b.Property<string>("Ward")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ITI");
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RoleLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RoleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Permissions")
                        .HasColumnType("text[]");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int?>("PhoneCountryId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TotpSecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TotpToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TotpTokenEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwoFaSetupStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserTotpBackUpCodes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneCountryId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Identity.UserOtp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OTPCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("OTPSentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OTPToken")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("Data.Entities.Log.SmsLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SmsType")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("Data.Entities.MotorEntity.Motor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("AgeOfVehicle")
                        .HasColumnType("integer");

                    b.Property<string>("ChasisNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("CompulsoryExcess")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CubicCapacity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("DateOfPurchase")
                        .HasColumnType("text");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsComprehensive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsThirdParty")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KilloWatt")
                        .HasColumnType("numeric");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Maintenance")
                        .HasColumnType("boolean");

                    b.Property<string>("ManufactureCompany")
                        .HasColumnType("text");

                    b.Property<string>("ManufactureYear")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("NCDYears")
                        .HasColumnType("integer");

                    b.Property<int>("NumberofSeatsIncludingDriver")
                        .HasColumnType("integer");

                    b.Property<bool?>("ParkingGarageOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ParkingPlaceGarage")
                        .HasColumnType("boolean");

                    b.Property<string>("PartyId")
                        .HasColumnType("text");

                    b.Property<bool>("PurchasedNewOld")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("RateOfDepreciation")
                        .HasColumnType("numeric");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<bool>("RiotStrike")
                        .HasColumnType("boolean");

                    b.Property<string>("SubModel")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalExcess")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueOfAccessories")
                        .HasColumnType("numeric");

                    b.Property<bool?>("VehicleForHireOrReward")
                        .HasColumnType("boolean");

                    b.Property<decimal>("VoluntaryExcess")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("YearsFromRegistrationDateYears")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YearsFromRegistrationDateYearsBS")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("Data.Entities.Payment.PaymentTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayTransactionId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentGatewayStatus")
                        .HasColumnType("text");

                    b.Property<string>("PolicyPurchaseId")
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Data.Entities.PrivateVehicleEntity.PrivateVehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessoriesDetail")
                        .HasColumnType("text");

                    b.Property<string>("AccidentOrLossInThreeYears")
                        .HasColumnType("text");

                    b.Property<string>("AgeForPrint")
                        .HasColumnType("text");

                    b.Property<string>("AgeForPrintEnglish")
                        .HasColumnType("text");

                    b.Property<decimal?>("AgeOfVehicle")
                        .HasColumnType("numeric");

                    b.Property<string>("AnyDisabilityOfEyeOrEarOfDriverCrimeAccustaion")
                        .HasColumnType("text");

                    b.Property<string>("AnyOtherInsuranceProposedVehicle")
                        .HasColumnType("text");

                    b.Property<string>("ChasisNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("CompulsoryExcess")
                        .HasColumnType("numeric");

                    b.Property<string>("CopyOfPolicyIfOtherVehicleAreInsuredInThisCompany")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CubicCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrentMarketPrice")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Days")
                        .HasColumnType("text");

                    b.Property<bool>("Depreciation")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DepreciationAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DepreciationRate")
                        .HasColumnType("numeric");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("text");

                    b.Property<bool>("EnterSumInsured")
                        .HasColumnType("boolean");

                    b.Property<string>("EntitledForNoClaimDiscountNCDFromOtherInsuranceCompany")
                        .HasColumnType("text");

                    b.Property<decimal>("GoodsCarryingCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("HasAnyComputerOrInsurer")
                        .HasColumnType("text");

                    b.Property<string>("HasProposersOrAnyOtherPersonsDrivingLicenseEverBeenCancelled")
                        .HasColumnType("text");

                    b.Property<bool>("HasSmartPolicy")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTailor")
                        .HasColumnType("boolean");

                    b.Property<bool>("ISRecoveryCharge")
                        .HasColumnType("boolean");

                    b.Property<string>("InsuranceCompanyName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAgentInvolved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComprehensive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDifferentlyAble")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDirectDiscountPA")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEntitledForNoClaimDiscountFromOtherInsuranceCompany")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIssued")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLayup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPersonalAccidentForPaidForDriver")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPersonalAccidentForPaidForPassenger")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivateTaxi")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProRataOrShortScale")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRiotStrikeAndTerrorismForDriver")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRiotStrikeAndTerrorismForPassenger")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsThirdParty")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVehicleDutyFree")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LayupDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LayupDaysEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LayupDaysStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Maintenance")
                        .HasColumnType("text");

                    b.Property<string>("ManufactureCompany")
                        .HasColumnType("text");

                    b.Property<string>("ManufactureYear")
                        .HasColumnType("text");

                    b.Property<string>("MasterPolicyNumber")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("NCDYears")
                        .HasColumnType("integer");

                    b.Property<int>("NumberofSeatsIncludingDriver")
                        .HasColumnType("integer");

                    b.Property<string>("PaToRiderAndOnePillionRiderSumInsuredAmount")
                        .HasColumnType("text");

                    b.Property<string>("ParkingGarageOpen")
                        .HasColumnType("text");

                    b.Property<string>("ParkingPlaceGarage")
                        .HasColumnType("text");

                    b.Property<string>("PartyId")
                        .HasColumnType("text");

                    b.Property<int>("PersonalAccidentForPassengerSeatCount")
                        .HasColumnType("integer");

                    b.Property<string>("PortfolioId")
                        .HasColumnType("text");

                    b.Property<int>("PreviousPolicyIssuedYear")
                        .HasColumnType("integer");

                    b.Property<string>("ProposerName")
                        .HasColumnType("text");

                    b.Property<bool>("PurchasedNewOld")
                        .HasColumnType("boolean");

                    b.Property<string>("PurposedVehicleUsedOtherThanThePurposer")
                        .HasColumnType("text");

                    b.Property<decimal?>("RateOfDepreciation")
                        .HasColumnType("numeric");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumberNepali")
                        .HasColumnType("text");

                    b.Property<string>("RenewalNoticeNCD")
                        .HasColumnType("text");

                    b.Property<bool>("Replacement")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ReplacementAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReplacementRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("RiotStrikeAndTerrorism")
                        .HasColumnType("boolean");

                    b.Property<int>("RiotStrikeAndTerrorismForPassengerSeatCount")
                        .HasColumnType("integer");

                    b.Property<string>("RiskType")
                        .HasColumnType("text");

                    b.Property<decimal?>("SpecialDiscountRate")
                        .HasColumnType("numeric");

                    b.Property<string>("SubModel")
                        .HasColumnType("text");

                    b.Property<decimal>("SumInsuredAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SumInsuredAmountForPaidDriver")
                        .HasColumnType("text");

                    b.Property<string>("SumInsuredAmountForPassenger")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalExcess")
                        .HasColumnType("numeric");

                    b.Property<bool>("Transportation")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TransportationAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TransportationRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("TypeOfInsurance")
                        .HasColumnType("integer");

                    b.Property<bool>("UseOfPrivateHire")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueOfAccessories")
                        .HasColumnType("text");

                    b.Property<int?>("ValueOfTailor")
                        .HasColumnType("integer");

                    b.Property<string>("ValueWithoutAccessories")
                        .HasColumnType("text");

                    b.Property<string>("VehicleForHireOrReward")
                        .HasColumnType("text");

                    b.Property<string>("VehiclePurpose")
                        .HasColumnType("text");

                    b.Property<decimal>("VoluntaryExcess")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("YearsFromRegistrationDateYears")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YearsFromRegistrationDateYearsBS")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrivateVehicles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.AdminEntity.Admin", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.AgentEntity.Agent", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.CorporateEntity.Corporate", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.CustomerEntity.Customer", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", "KycReviewedByUser")
                        .WithMany()
                        .HasForeignKey("KycReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KycReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.CustomerEntity.CustomerAddress", b =>
                {
                    b.HasOne("Data.Entities.CustomerEntity.Customer", "customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Data.Entities.Draft.PolicyDraft", b =>
                {
                    b.HasOne("Data.Entities.CustomerEntity.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.ITIEntity.InternationalTravelInsurance", "ITI")
                        .WithMany()
                        .HasForeignKey("ITIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.MotorEntity.Motor", "Motor")
                        .WithMany()
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.Payment.PaymentTransaction", "PaymentTransaction")
                        .WithOne("PolicyDraft")
                        .HasForeignKey("Data.Entities.Draft.PolicyDraft", "PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.PrivateVehicleEntity.PrivateVehicle", "privateVehicle")
                        .WithMany()
                        .HasForeignKey("privateVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("ITI");

                    b.Navigation("Motor");

                    b.Navigation("PaymentTransaction");

                    b.Navigation("privateVehicle");
                });

            modelBuilder.Entity("Data.Entities.ITIEntity.ITIFamilyMember", b =>
                {
                    b.HasOne("Data.Entities.ITIEntity.InternationalTravelInsurance", "InternationalTravelInsurance")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("InternationalTravelInsuranceId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InternationalTravelInsurance");
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Data.Entities.Common.Country", "PhoneCountry")
                        .WithMany()
                        .HasForeignKey("PhoneCountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhoneCountry");
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationUserRoles", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Identity.UserOtp", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Otp")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.CustomerEntity.Customer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Data.Entities.ITIEntity.InternationalTravelInsurance", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Otp");
                });

            modelBuilder.Entity("Data.Entities.Payment.PaymentTransaction", b =>
                {
                    b.Navigation("PolicyDraft");
                });
#pragma warning restore 612, 618
        }
    }
}
