<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
  <PackageReference Include="PdfSharp" Version="8.0.0" />
  <PackageReference Include="PdfSharp.Charting" Version="8.0.0" />
  <PackageReference Include="MigraDoc.DocumentObjectModel" Version="8.0.0" />
  <PackageReference Include="MigraDoc.Rendering" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Data\Data\Data.csproj" />
    <ProjectReference Include="..\..\Business.Common\Business.Common.csproj" />
    <ProjectReference Include="..\..\Business.CustomerPortalApi\Business.BeemaEdgeApi.csproj" />
  </ItemGroup>

</Project>
