<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.20.0" />
    <PackageReference Include="Hangfire.Core" Version="1.8.15" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.6.2" />
    <PackageReference Include="Minio" Version="6.0.4" />
    <PackageReference Include="Otp.NET" Version="1.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
    <PackageReference Include="NPOI" Version="2.7.1" />
    <PackageReference Include="PDFsharp" Version="6.2.3" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\Data\Data.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.Common\Infrastructure.Common.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.CoreApi\Infrastructure.CoreApi\Infrastructure.CoreApi.csproj" />
    <ProjectReference Include="..\..\Models\Models\Models.csproj" />
    <ProjectReference Include="..\..\SharedKernel\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constant\" />
  </ItemGroup>

</Project>
