<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.15" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.6.2" />
    <PackageReference Include="Minio" Version="6.0.4" />
    <PackageReference Include="Otp.NET" Version="1.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\Data\Data.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.CoreApi\Infrastructure.CoreApi\Infrastructure.CoreApi.csproj" />
    <ProjectReference Include="..\..\Models\Models\Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constant\" />
  </ItemGroup>

</Project>
