# ----------------- BASE IMAGE -----------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libfontconfig1 \
    fontconfig \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8080
EXPOSE 8081

# ----------------- BUILD IMAGE -----------------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy only projects needed for Web API
COPY ["src/Web/BeemaEdgeApi.csproj", "src/Web/"]
COPY ["src/Data/Data/Data.csproj", "src/Data/Data/"]
COPY ["src/Business/Business.Common/Business.Common.csproj", "src/Business/Business.Common/"]
COPY ["src/Models/Models/Models.csproj", "src/Models/Models/"]
COPY ["src/SharedKernel/SharedKernel/SharedKernel.csproj", "src/SharedKernel/SharedKernel/"]
COPY ["src/Infrastructure/Infrastructure.Common/Infrastructure.Common.csproj", "src/Infrastructure/Infrastructure.Common/"]
COPY ["src/Business/Business.CustomerPortalApi/Business.BeemaEdgeApi.csproj", "src/Business/Business.CustomerPortalApi/"]

# Restore dependencies only for Web API projects
RUN dotnet restore "src/Web/BeemaEdgeApi.csproj"

# Copy the source code
COPY . .

# Build Web API
WORKDIR "/src/src/Web"
RUN dotnet build "BeemaEdgeApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# ----------------- PUBLISH IMAGE -----------------
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR "/src/src/Web"
RUN dotnet publish "BeemaEdgeApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# ----------------- FINAL IMAGE -----------------
FROM base AS final
WORKDIR /app

# Copy published files
COPY --from=publish /app/publish .

# Add fonts
RUN mkdir -p /usr/share/fonts/truetype/nirmala
COPY --from=build /src/src/Web/Assets/Fonts/Nirmala.ttf /usr/share/fonts/truetype/nirmala/Nirmala.ttf
RUN chmod 644 /usr/share/fonts/truetype/nirmala/Nirmala.ttf && fc-cache -f -v

# Security: non-root user
RUN groupadd -r appuser && useradd -r -g appuser appuser
RUN chown -R appuser:appuser /app
USER appuser

ENTRYPOINT ["dotnet", "BeemaEdgeApi.dll"]
